# DO NOT EDIT THIS FILE
#
# Any changes to this file will not have any effect and will be overwritten
# when the source tree is updated. If you need to make changes copy this file
# to config.local.mk and make your changes there (remember to uncomment the
# lines you want to override).

###################### Build Environment Configuration #########################

ifdef _INC_BUILDCONFIG

# The maximum number of make jobs to run in parallel when building a package.
#MAKE_MAXJOBS=20

# The maximum system load for make. If the system load is above this, make will
# wait for it to drop below this before starting any new jobs.
#MAKE_MAXLOAD=3.5

#MAKE_FLAGS=-j $(MAKE_MAXJOBS) -l $(MAKE_MAXLOAD)

# The default action to take when installing new files on package upgrades.
# Note that this affects only installpkg/upgradepkg; it has no bearing on how
# the packages are created. See `man 8 pkgtool` for a list of supported
# actions.
#NEW_FILE_ACTION=

endif

############################ System Configuration ##############################

ifdef _INC_SYSCONFIG

# General system configuration
#OS_NAME:=Fidelix
#OS_NAME_LOWERCASE:=fidelix
#OS_DESCRIPTION:=Fidelix Linux
#OS_MAJOR:=0
#OS_MINOR:=1
#OS_VERSION:=$(OS_MAJOR).$(OS_MINOR)
#OS_RELEASE_NAME:=Arthur
#OS_SRC_DIR:=/usr/src

# Package file configuration
#OS_PKG_TAG:=arthur
#PKG_EXTENSION:=tgz

# Set the system architecture
#OS_ARCH:=x86_64
#OS_TARGET_TRIPLET:=$(OS_ARCH)-$(OS_NAME_LOWERCASE)-linux-musl

# Set the system type. On Intel/AMD systems, generic-$(OS_ARCH) is usually
# sufficient. On embedded systems, it may be necessary to specify a different
# system to get the correct kernel and bootloader installed. A list of
# supported systems can be found by examining the include/system directory.
#OS_SYSTEM:=generic-$(OS_ARCH)

endif

########################## Bootstrap Configuration #############################

# NOTE: Configuration in this section affects only the bootstrap directory.

ifdef _INC_BSCONFIG

# The prefix to place the bootstrap environment in.
# NOTE: If you change this you must also update bootstrap/tools/Makefile
#PREFIX=/opt/bootstrap

# The name of the tar archive to save the bootstrap in.
#OUTPUT_FILE=bootstrap.tar

# Whether or not to run the test suites. Set to true to run them, or false to
# skip them.
#RUN_TESTS=true

# The maximum number of make jobs to run in parallel.
#MAXJOBS=3

# The architecture to target. Note that the host system **must** be able to run
# binaries produced for this architecture.
#ARCH=x86_64

# The ID for the bootstrap distribution in the host triplet.
#DISTID=bootstrap

#TARGET=$(ARCH)-$(DISTID)-linux-musl

endif

