#!/bin/sh

# DESCRIPTION Perform the initial system configuration

basedir=$(realpath $(dirname $0))

# Set the hostname
eval $basedir/hostname

# Set a root password
eval $basedir/root-password

# Set the timezone
eval $basedir/timezone

# Network interfaces
eval $basedir/network

# Enable the default services and bring up the service menu
echo Enabling default services
service all default
eval $basedir/services

