#!/bin/sh

# DESCRIPTION Set the root password

read -p "Would you like to set a root password [y/n]: " prompt
until [ "$prompt" == "y" ] || [ "$prompt" == "n" ]; do
	read -p "[y/n]: " prompt
done

[ "$prompt" == "n" ] && exit
passwd

