DIR:=daemon

# Packages contained in this directory
PACKAGES=\
	openssh \
	nginx \
	openntpd

# Non-package subdirectories contained in this directory that should be
# included when searching for packages
SUBDIRS=

include dir.mk

