DIR:=util

# Packages contained in this directory
PACKAGES=\
	libuuid \
	gptfdisk \
	xorriso \
	libgcc

DEFAULT_PACKAGES=\
	libuuid \
	gptfdisk

# Non-package subdirectories contained in this directory that should be
# included when searching for packages
SUBDIRS=

include dir.mk

