DIR:=util

# Packages contained in this directory
PACKAGES=\
	libuuid \
	gptfdisk \
	xorriso \
	libstdcxx \
	libedit \
	pcre \
	iptables \
	bsdtar

DEFAULT_PACKAGES=\
	libuuid \
	gptfdisk \
	xorriso \
	libedit \
	pcre \
	iptables

# Non-package subdirectories contained in this directory that should be
# included when searching for packages
SUBDIRS=

# Subdirectories that should have Make run on them but do not produce binary
# packages.
TARGETS=\
	pkgsrc \
	cross-tools

include dir.mk

