DIR:=base

# Packages contained in this directory
PACKAGES=\
	aaa-directory-skel \
	aaa-file-skel \
	linux-headers \
	pkgtools \
	musl \
	zlib \
	binutils \
	m4 \
	gmp \
	mpfr \
	mpc \
	libstdcxx \
	gcc \
	libressl \
	system-scripts \
	busybox \
	make \
	perl \
	texinfo \
	mandoc \
	man-pages \
	zoneinfo \
	ncurses \
	bison \
	flex \
	libelf \
	kmod

# Non-package subdirectories contained in this directory that should be
# included when searching for packages
SUBDIRS=

include dir.mk

